/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AutoComplete {
    'autocompleteIdentifier': string;
    'name': string;
  }
  interface AutoCompleteAttributes extends StencilHTMLAttributes {
    'autocompleteIdentifier'?: string;
    'name'?: string;
    'onAutocomplete:placeChange'?: (event: CustomEvent) => void;
    'onReady'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AutoComplete': Components.AutoComplete;
  }

  interface StencilIntrinsicElements {
    'auto-complete': Components.AutoCompleteAttributes;
  }


  interface HTMLAutoCompleteElement extends Components.AutoComplete, HTMLStencilElement {}
  var HTMLAutoCompleteElement: {
    prototype: HTMLAutoCompleteElement;
    new (): HTMLAutoCompleteElement;
  };

  interface HTMLElementTagNameMap {
    'auto-complete': HTMLAutoCompleteElement
  }

  interface ElementTagNameMap {
    'auto-complete': HTMLAutoCompleteElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
